publish_to: none
name: flutter_web_howl
description: A new Flutter web package that import & wrap the Howl.js library, to be used in Web Plugin
version: 1.0.0
homepage: https://github.com/florent37/flutter_web_howl

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  import_js_library:
    git: git://https://github.com/JollyTechnologies/flutter_web_import_js_library_null_safety.git
#    ref: master
  js: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/howler.js

